services:
  app:
    container_name: learning-golang
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: learning-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: learningdb
    ports:
      - "5432:5432"